{% set name = "batoid" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37de7605e0699c63fe46cc07bd536ee8cc7e65d92fc2722f7ce69d1e7c4ca0d8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
  skip: true  # [py==38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - numpy
    - pytest-runner
  run:
    - python
    - pyyaml
    - scipy
    - galsim
    - matplotlib-base
    - astropy-base

test:
  imports:
    - batoid
  requires:
    - pip
  # commands:
  #   # fails due to galsim requirement on setuptools
  #   - pip check

about:
  home: https://github.com/jmeyers314/batoid
  summary: 'c++ backed python optical raytracer'
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - jmeyers314
